export const GET_PRODUCTS_REQUEST = "GET_PRODUCTS_REQUEST";
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_FAIL = "GET_PRODUCTS_FAIL";

export const GET_PRODUCTS_DETAILS_REQUEST = "GET_PRODUCTS_DETAILS_REQUEST";
export const GET_PRODUCTS__DETAILS_SUCCESS = "GET_PRODUCTS__DETAILS_SUCCESS";
export const GET_PRODUCTS__DETAILS_FAIL = "GET_PRODUCTS_DETAILS__FAIL";
export const GET_PRODUCTS__DETAILS_RESET = "GET_PRODUCTS_DETAILS__RESET";
